version: 2.1

orbs:
  nx: nrwl/nx@1.6.2
  node: circleci/node@6.3.0

commands:
  setup:
    description: "Setup"
    steps:
      - checkout
      - node/install-pnpm:
          version: '9'
      - run:
          name: Install pnpm dependencies
          command: pnpm install
      - nx/set-shas
      - run:
          name: Build
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=build

jobs:
  lint:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - run:
          name: Lint
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=lint
  test:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - run:
          name: Unit Tests
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=test

  typecheck:
    executor:
      name: node/default
      tag: '22.10'
    steps:
      - setup
      - run:
          name: Typecheck
          command: pnpm nx affected --base=$NX_BASE --head=$NX_HEAD --target=typecheck

workflows:
  main:
    jobs:
      - lint
      - test
      - typecheck
